"""
Export a trained DQN V2 checkpoint to a standalone numpy submission agent.

Usage:
    python src/utils/export_to_numpy.py \
        --checkpoint src/agents/dqn_v2.pt \
        --output     src/agents/agent_DQN_numpy.py

The generated file is a single .py that:
  - imports only numpy (no torch)
  - embeds all network weights as base64-encoded bytes
  - implements the full forward pass and feature extraction in numpy
  - contains class MyAgent(BaseAgent) ready for Codabench submission
"""

import argparse
import base64
import sys
from pathlib import Path

import numpy as np
import torch

root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(root))

from src.agents.agent_DQN_v2 import DQNAgentV2


# ── Weight encoding ─────────────────────────────────────────────────────────────

def _encode(arr: np.ndarray) -> str:
    """Encode a numpy array as a base64 string of float32 bytes."""
    b64 = base64.b64encode(arr.astype(np.float32).tobytes()).decode('ascii')
    # Break into 80-char lines inside the string literal for readability
    lines = [b64[i:i+80] for i in range(0, len(b64), 80)]
    return '\n'.join(lines)


# ── Code generation ─────────────────────────────────────────────────────────────

def generate_submission(weights: dict, output_path: Path):
    """Write a self-contained numpy agent .py to output_path."""

    # Collect layers in forward order: net.0.weight/bias, net.2.weight/bias, net.4.weight/bias
    layers = []
    for i in [0, 2, 4]:
        W = weights[f'net.{i}.weight']   # shape (out, in)
        b = weights[f'net.{i}.bias']     # shape (out,)
        layers.append((W, b))

    def var_block(name, arr):
        shape = arr.shape
        enc   = _encode(arr)
        lines = enc.split('\n')
        # multiline string with continuation
        quoted = '"' + ('"\n    "'.join(lines)) + '"'
        return (
            f"_{name}_b64 = (\n    {quoted}\n)\n"
            f"_{name} = np.frombuffer(base64.b64decode(_{name}_b64), dtype=np.float32)"
            f".reshape({shape})\n"
        )

    weight_section = ""
    for idx, (W, b) in enumerate(layers):
        weight_section += var_block(f"W{idx}", W)
        weight_section += var_block(f"b{idx}", b)
        weight_section += "\n"

    code = f'''\
"""
Standalone numpy DQN agent for the Sailing Challenge — Codabench submission.
Generated by src/utils/export_to_numpy.py from a trained DQN V2 checkpoint.

Network: {layers[0][0].shape[1]}-dim features → {layers[0][0].shape[0]} → {layers[1][0].shape[0]} → {layers[2][0].shape[0]} actions
No external dependencies beyond numpy.
"""

import base64
import numpy as np

try:
    from evaluator.base_agent import BaseAgent   # Codabench runtime
except ImportError:
    from agents.base_agent import BaseAgent       # local dev


# ── Embedded weights (base64-encoded float32) ──────────────────────────────────

{weight_section}

# ── Constants ──────────────────────────────────────────────────────────────────

_GOAL = np.array([64.0, 127.0])

_ACTIONS_VEC = np.array([
    ( 0.,  1.), ( 1.,  1.), ( 1.,  0.), ( 1., -1.),
    ( 0., -1.), (-1., -1.), (-1.,  0.), (-1.,  1.),
    ( 0.,  0.),
], dtype=np.float32)

_DIRS8 = [(0,1),(1,1),(1,0),(1,-1),(0,-1),(-1,-1),(-1,0),(-1,1)]


# ── Sailing physics ─────────────────────────────────────────────────────────────

def _compute_efficiencies(wind_vec):
    wspd = float(np.linalg.norm(wind_vec))
    if wspd < 1e-8:
        return np.full(9, 0.05, dtype=np.float32)
    wd = wind_vec / wspd
    effs = np.zeros(9, dtype=np.float32)
    for i, a in enumerate(_ACTIONS_VEC):
        an = float(np.linalg.norm(a))
        if an < 1e-8:
            continue
        cos_a = float(np.clip(np.dot(a / an, wd), -1.0, 1.0))
        deg   = np.degrees(np.arccos(cos_a))
        if deg < 45:
            effs[i] = 0.05
        elif deg < 90:
            effs[i] = 0.5 + 0.5 * (deg - 45) / 45.0
        elif deg <= 135:
            effs[i] = 1.0
        else:
            effs[i] = 1.0 - 0.5 * (deg - 135) / 45.0
    return effs


# ── Feature extraction (70-dim) ────────────────────────────────────────────────

def _extract_features(obs):
    x, y   = float(obs[0]), float(obs[1])
    vx, vy = float(obs[2]), float(obs[3])
    wx, wy = float(obs[4]), float(obs[5])

    wind_field = obs[6          : 6 + 32768  ].reshape(128, 128, 2)
    world_map  = obs[6 + 32768  : 6 + 32768 + 16384].reshape(128, 128)

    ix = int(np.clip(x, 0, 127))
    iy = int(np.clip(y, 0, 127))

    gdx   = _GOAL[0] - x
    gdy   = _GOAL[1] - y
    gdist = float(np.sqrt(gdx**2 + gdy**2)) + 1e-8

    f_goal = np.array([gdx / 127.0, gdy / 127.0, gdist / 180.0], dtype=np.float32)
    f_pos  = np.array([x / 127.0, y / 127.0],                    dtype=np.float32)
    f_dir  = np.array([gdx / gdist, gdy / gdist],                 dtype=np.float32)

    vn    = float(np.sqrt(vx**2 + vy**2))
    f_vel = np.array([vx / 8.0, vy / 8.0, vn / 8.0], dtype=np.float32)

    wspd   = float(np.sqrt(wx**2 + wy**2)) + 1e-8
    f_wind = np.array([wx / 15.0, wy / 15.0, wspd / 15.0], dtype=np.float32)

    f_eff = _compute_efficiencies(np.array([wx, wy]))

    DISTS = [4, 10, 20]
    f_obs = np.zeros(24, dtype=np.float32)
    for k, (dx_o, dy_o) in enumerate(_DIRS8):
        for j, d in enumerate(DISTS):
            nx = int(np.clip(ix + dx_o * d, 0, 127))
            ny = int(np.clip(iy + dy_o * d, 0, 127))
            f_obs[k * 3 + j] = world_map[ny, nx]

    FRACS = [0.05, 0.15, 0.30, 0.50, 0.70, 0.85, 0.95, 1.00]
    f_path = np.zeros(24, dtype=np.float32)
    for i, frac in enumerate(FRACS):
        px = int(np.clip(x + gdx * frac, 0, 127))
        py = int(np.clip(y + gdy * frac, 0, 127))
        f_path[3 * i]     = world_map[py, px]
        f_path[3 * i + 1] = wind_field[py, px, 0] / 15.0
        f_path[3 * i + 2] = wind_field[py, px, 1] / 15.0

    return np.concatenate([f_goal, f_pos, f_dir, f_vel, f_wind, f_eff, f_obs, f_path])


# ── Numpy forward pass ─────────────────────────────────────────────────────────

def _forward(x):
    h = np.maximum(0.0, x @ _W0.T + _b0)
    h = np.maximum(0.0, h @ _W1.T + _b1)
    return h @ _W2.T + _b2


# ── Agent ──────────────────────────────────────────────────────────────────────

class MyAgent(BaseAgent):
    """
    DQN sailing agent — pure numpy, no torch.
    Network: {layers[0][0].shape[1]} → {layers[0][0].shape[0]} → {layers[1][0].shape[0]} → {layers[2][0].shape[0]}
    """

    def act(self, observation: np.ndarray) -> int:
        feats  = _extract_features(observation)
        q_vals = _forward(feats)
        return int(np.argmax(q_vals))

    def reset(self) -> None:
        pass

    def seed(self, seed=None) -> None:
        if seed is not None:
            np.random.seed(seed)
'''

    output_path.write_text(code, encoding='utf-8')
    print(f"  Generated → {output_path}")
    size_kb = output_path.stat().st_size / 1024
    print(f"  File size : {size_kb:.1f} KB")


# ── CLI ─────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(description="Export DQN V2 checkpoint to numpy agent.")
    parser.add_argument("--checkpoint", required=True,
                        help="Path to .pt checkpoint (e.g. src/agents/dqn_v2.pt)")
    parser.add_argument("--output",     required=True,
                        help="Output .py path (e.g. src/agents/agent_DQN_numpy.py)")
    args = parser.parse_args()

    ckpt_path = Path(args.checkpoint)
    out_path  = Path(args.output)

    if not ckpt_path.exists():
        print(f"  Error: checkpoint not found at {ckpt_path}")
        sys.exit(1)

    print(f"  Loading checkpoint: {ckpt_path}")
    agent   = DQNAgentV2.load(str(ckpt_path))
    weights = agent.get_numpy_weights()

    print("  Network weight shapes:")
    for k, v in weights.items():
        print(f"    {k:30s}: {v.shape}")

    generate_submission(weights, out_path)
    print("  Done. To validate:")
    print(f"    python src/test_agent_validity.py {out_path}")


if __name__ == "__main__":
    main()