"""
Export a trained PPO checkpoint to a standalone numpy submission agent.

Usage:
    python src/utils/export_ppo_to_numpy.py \
        --checkpoint src/agents/ppo_agent.pt \
        --output     src/agents/agent_PPO_numpy.py

The generated file:
  - imports only numpy (no torch)
  - embeds all actor-network weights as base64-encoded bytes
  - implements conv2d, linear, and the full forward pass in numpy
  - contains class MyAgent(BaseAgent) ready for Codabench submission

Architecture (actor only — critic head is discarded):
  scalar(6) ──► Linear(6→32)→ReLU→Linear(32→64)→ReLU             ─┐
  wind(2,128,128) ──► 3×Conv2d+ReLU → Flatten → Linear→ReLU        ├─► trunk(256→128→64) → actor_head(64→9)
  world(1,128,128) ──► 3×Conv2d+ReLU → Flatten → Linear→ReLU      ─┘
"""

import argparse
import base64
import sys
from pathlib import Path

import numpy as np
import torch

root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(root))

from src.agents.agent_PPO import PPOAgent


# ── Weight encoding ──────────────────────────────────────────────────────────────

def _encode(arr: np.ndarray) -> str:
    """Encode a numpy array as a base64 string of float32 bytes (80-char lines)."""
    b64 = base64.b64encode(arr.astype(np.float32).tobytes()).decode('ascii')
    lines = [b64[i:i+80] for i in range(0, len(b64), 80)]
    return '\n'.join(lines)


# ── Code generation ──────────────────────────────────────────────────────────────

# Layers to extract (actor only — skip critic_head)
_LAYER_KEYS = [
    'scalar_branch.0',
    'scalar_branch.2',
    'wind_branch.0',
    'wind_branch.2',
    'wind_branch.4',
    'wind_branch.7',
    'world_branch.0',
    'world_branch.2',
    'world_branch.4',
    'world_branch.7',
    'trunk.0',
    'trunk.2',
    'actor_head',
]


def _var_name(layer_key: str, suffix: str) -> str:
    """Convert 'wind_branch.0' + 'W' → '_wind_branch_0_W'."""
    return '_' + layer_key.replace('.', '_') + '_' + suffix


def _var_block(var_name: str, arr: np.ndarray) -> str:
    """Generate base64 decode + reshape block for one weight tensor."""
    shape = arr.shape
    enc   = _encode(arr)
    lines = enc.split('\n')
    quoted = '"' + ('"\n    "'.join(lines)) + '"'
    return (
        f"{var_name}_b64 = (\n    {quoted}\n)\n"
        f"{var_name} = np.frombuffer(base64.b64decode({var_name}_b64), dtype=np.float32)"
        f".reshape({shape})\n"
    )


def generate_submission(weights: dict, output_path: Path):
    """Write a self-contained numpy PPO agent to output_path."""

    weight_section = ""
    for key in _LAYER_KEYS:
        W = weights[f'{key}.weight']
        b = weights[f'{key}.bias']
        weight_section += _var_block(_var_name(key, 'W'), W)
        weight_section += _var_block(_var_name(key, 'b'), b)
        weight_section += '\n'

    # Print architecture summary in docstring
    sb0_shape = weights['scalar_branch.0.weight'].shape
    ah_shape  = weights['actor_head.weight'].shape

    code = f'''\
"""
Standalone numpy PPO agent for the Sailing Challenge — Codabench submission.
Generated by src/utils/export_ppo_to_numpy.py from a trained PPO checkpoint.

Architecture (actor only):
  scalar(6) → Linear(6→32)→ReLU→Linear(32→64)→ReLU  ─┐
  wind(2,128,128) → 3xConv2d+ReLU → Linear→ReLU        ├─► trunk(256→128→64) → {ah_shape[0]} actions
  world(1,128,128) → 3xConv2d+ReLU → Linear→ReLU      ─┘
No external dependencies beyond numpy.
"""

import base64
import numpy as np

try:
    from evaluator.base_agent import BaseAgent   # Codabench runtime
except ImportError:
    from agents.base_agent import BaseAgent       # local dev


# ── Embedded weights (base64-encoded float32) ─────────────────────────────────

{weight_section}

# ── Numpy conv2d (Conv2d + ReLU, no padding) ─────────────────────────────────

def _conv2d(x, W, b, stride):
    """
    x: (C_in, H, W)  W: (C_out, C_in, kH, kW)  b: (C_out,)
    Returns (C_out, H_out, W_out) after ReLU.
    Uses stride_tricks im2col — no Python loops over spatial dims.
    """
    x = np.ascontiguousarray(x, dtype=np.float32)
    C_in, H, Wi = x.shape
    C_out, _, kH, kW = W.shape
    Ho = (H  - kH) // stride + 1
    Wo = (Wi - kW) // stride + 1
    shape   = (Ho, Wo, C_in, kH, kW)
    strides = (x.strides[1] * stride, x.strides[2] * stride,
               x.strides[0], x.strides[1], x.strides[2])
    windows = np.lib.stride_tricks.as_strided(x, shape=shape, strides=strides)
    # (Ho*Wo, C_in*kH*kW) @ (C_out, C_in*kH*kW).T + b → (Ho*Wo, C_out)
    out = windows.reshape(Ho * Wo, -1) @ W.reshape(C_out, -1).T + b
    return np.maximum(0.0, out.reshape(Ho, Wo, C_out).transpose(2, 0, 1))


# ── Numpy forward pass (actor head only) ─────────────────────────────────────

def _forward(obs):
    scalar     = obs[:6          ].astype(np.float32)
    wind_flat  = obs[6:6+32768   ].astype(np.float32)
    world_flat = obs[6+32768:6+32768+16384].astype(np.float32)

    wind  = wind_flat.reshape(2, 128, 128)
    world = world_flat.reshape(1, 128, 128)

    # ── Scalar branch ─────────────────────────────────────────────────────────
    s = np.maximum(0.0, scalar @ _scalar_branch_0_W.T + _scalar_branch_0_b)
    s = np.maximum(0.0, s      @ _scalar_branch_2_W.T + _scalar_branch_2_b)

    # ── Wind branch (CNN) ─────────────────────────────────────────────────────
    w = _conv2d(wind, _wind_branch_0_W, _wind_branch_0_b, stride=4)
    w = _conv2d(w,    _wind_branch_2_W, _wind_branch_2_b, stride=2)
    w = _conv2d(w,    _wind_branch_4_W, _wind_branch_4_b, stride=2)
    w = w.reshape(-1)
    w = np.maximum(0.0, w @ _wind_branch_7_W.T + _wind_branch_7_b)

    # ── World branch (CNN) ────────────────────────────────────────────────────
    m = _conv2d(world, _world_branch_0_W, _world_branch_0_b, stride=4)
    m = _conv2d(m,     _world_branch_2_W, _world_branch_2_b, stride=2)
    m = _conv2d(m,     _world_branch_4_W, _world_branch_4_b, stride=2)
    m = m.reshape(-1)
    m = np.maximum(0.0, m @ _world_branch_7_W.T + _world_branch_7_b)

    # ── Shared trunk ──────────────────────────────────────────────────────────
    h = np.concatenate([s, w, m])
    h = np.maximum(0.0, h @ _trunk_0_W.T + _trunk_0_b)
    h = np.maximum(0.0, h @ _trunk_2_W.T + _trunk_2_b)

    # ── Actor head (logits over 9 actions) ────────────────────────────────────
    return h @ _actor_head_W.T + _actor_head_b


# ── Agent ─────────────────────────────────────────────────────────────────────

class MyAgent(BaseAgent):
    """PPO sailing agent — pure numpy, no torch. Greedy w.r.t. policy logits."""

    def act(self, observation: np.ndarray) -> int:
        return int(np.argmax(_forward(observation)))

    def reset(self) -> None:
        pass

    def seed(self, seed=None) -> None:
        if seed is not None:
            np.random.seed(seed)
'''

    output_path.write_text(code, encoding='utf-8')
    print(f"  Generated → {output_path}")
    print(f"  File size : {output_path.stat().st_size / 1024:.1f} KB")


# ── CLI ──────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Export a trained PPO checkpoint to a standalone numpy agent.")
    parser.add_argument("--checkpoint", required=True,
                        help="Path to .pt checkpoint (e.g. src/agents/ppo_agent.pt)")
    parser.add_argument("--output", required=True,
                        help="Output .py path (e.g. src/agents/agent_PPO_numpy.py)")
    args = parser.parse_args()

    ckpt_path = Path(args.checkpoint)
    out_path  = Path(args.output)

    if not ckpt_path.exists():
        print(f"  Error: checkpoint not found at {ckpt_path}")
        sys.exit(1)

    print(f"  Loading checkpoint: {ckpt_path}")
    checkpoint = torch.load(str(ckpt_path), map_location='cpu', weights_only=False)
    state_dict = checkpoint['network']
    weights = {k: v.cpu().numpy() for k, v in state_dict.items()}

    print("  Network weight shapes:")
    for key in _LAYER_KEYS:
        W = weights[f'{key}.weight']
        b = weights[f'{key}.bias']
        print(f"    {key+'.weight':35s}: {str(W.shape):20s}  {key+'.bias':35s}: {b.shape}")

    generate_submission(weights, out_path)
    print("  Done. To validate:")
    print(f"    python src/test_agent_validity.py {out_path}")


if __name__ == "__main__":
    main()