"""
Export a trained DQN (CNN) checkpoint to a standalone numpy submission agent.

Usage:
    python src/utils/export_dqn_cnn_to_numpy.py \
        --checkpoint src/agents/dqn_cnn.pt \
        --output     src/agents/agent_DQN_cnn_numpy.py

Architecture:
  scalar(6) ──► Linear(6→32)→ReLU→Linear(32→64)→ReLU             ─┐
  wind(2,128,128) ──► 3×Conv2d+ReLU → Flatten → Linear(1152→128)   ├─► fusion(256→128→64→9)
  world(1,128,128) ──► 3×Conv2d+ReLU → Flatten → Linear(576→64)   ─┘
"""

import argparse
import base64
import sys
from pathlib import Path

import numpy as np
import torch

root = Path(__file__).resolve().parent.parent.parent
sys.path.insert(0, str(root))


# ── Weight encoding ──────────────────────────────────────────────────────────────

def _encode(arr: np.ndarray) -> str:
    b64 = base64.b64encode(arr.astype(np.float32).tobytes()).decode('ascii')
    lines = [b64[i:i+80] for i in range(0, len(b64), 80)]
    return '\n'.join(lines)


# ── Layer keys to export ─────────────────────────────────────────────────────────

_LAYER_KEYS = [
    'scalar_branch.0',
    'scalar_branch.2',
    'wind_branch.0',
    'wind_branch.2',
    'wind_branch.4',
    'wind_branch.7',
    'world_branch.0',
    'world_branch.2',
    'world_branch.4',
    'world_branch.7',
    'fusion.0',
    'fusion.2',
    'fusion.4',
]


def _var_name(layer_key: str, suffix: str) -> str:
    return '_' + layer_key.replace('.', '_') + '_' + suffix


def _var_block(var_name: str, arr: np.ndarray) -> str:
    shape  = arr.shape
    enc    = _encode(arr)
    lines  = enc.split('\n')
    quoted = '"' + ('"\n    "'.join(lines)) + '"'
    return (
        f"{var_name}_b64 = (\n    {quoted}\n)\n"
        f"{var_name} = np.frombuffer(base64.b64decode({var_name}_b64), dtype=np.float32)"
        f".reshape({shape})\n"
    )


def generate_submission(weights: dict, output_path: Path):
    weight_section = ""
    for key in _LAYER_KEYS:
        W = weights[f'{key}.weight']
        b = weights[f'{key}.bias']
        weight_section += _var_block(_var_name(key, 'W'), W)
        weight_section += _var_block(_var_name(key, 'b'), b)
        weight_section += '\n'

    code = f'''\
"""
Standalone numpy DQN (CNN) agent for the Sailing Challenge — Codabench submission.
Generated by src/utils/export_dqn_cnn_to_numpy.py from a trained DQN checkpoint.

Architecture:
  scalar(6) -> Linear(6->32)->ReLU->Linear(32->64)->ReLU  --+
  wind(2,128,128) -> 3xConv2d+ReLU -> Linear->ReLU           +--> fusion(256->128->64->9)
  world(1,128,128) -> 3xConv2d+ReLU -> Linear->ReLU         --+
No external dependencies beyond numpy.
"""

import base64
import numpy as np

try:
    from evaluator.base_agent import BaseAgent   # Codabench runtime
except ImportError:
    from agents.base_agent import BaseAgent       # local dev


# ── Embedded weights (base64-encoded float32) ─────────────────────────────────

{weight_section}

# ── Numpy conv2d (Conv2d + ReLU, no padding) ─────────────────────────────────

def _conv2d(x, W, b, stride):
    """x: (C_in,H,W), W: (C_out,C_in,kH,kW), b: (C_out,) -> (C_out,H_out,W_out) after ReLU."""
    x = np.ascontiguousarray(x, dtype=np.float32)
    C_in, H, Wi = x.shape
    C_out, _, kH, kW = W.shape
    Ho = (H  - kH) // stride + 1
    Wo = (Wi - kW) // stride + 1
    shape   = (Ho, Wo, C_in, kH, kW)
    strides = (x.strides[1] * stride, x.strides[2] * stride,
               x.strides[0], x.strides[1], x.strides[2])
    windows = np.lib.stride_tricks.as_strided(x, shape=shape, strides=strides)
    out = windows.reshape(Ho * Wo, -1) @ W.reshape(C_out, -1).T + b
    return np.maximum(0.0, out.reshape(Ho, Wo, C_out).transpose(2, 0, 1))


# ── Numpy forward pass ────────────────────────────────────────────────────────

def _forward(obs):
    scalar     = obs[:6          ].astype(np.float32)
    wind_flat  = obs[6:6+32768   ].astype(np.float32)
    world_flat = obs[6+32768:6+32768+16384].astype(np.float32)

    wind  = wind_flat.reshape(2, 128, 128)
    world = world_flat.reshape(1, 128, 128)

    # Scalar branch
    s = np.maximum(0.0, scalar @ _scalar_branch_0_W.T + _scalar_branch_0_b)
    s = np.maximum(0.0, s      @ _scalar_branch_2_W.T + _scalar_branch_2_b)

    # Wind branch (CNN)
    w = _conv2d(wind, _wind_branch_0_W, _wind_branch_0_b, stride=4)
    w = _conv2d(w,    _wind_branch_2_W, _wind_branch_2_b, stride=2)
    w = _conv2d(w,    _wind_branch_4_W, _wind_branch_4_b, stride=2)
    w = w.reshape(-1)
    w = np.maximum(0.0, w @ _wind_branch_7_W.T + _wind_branch_7_b)

    # World branch (CNN)
    m = _conv2d(world, _world_branch_0_W, _world_branch_0_b, stride=4)
    m = _conv2d(m,     _world_branch_2_W, _world_branch_2_b, stride=2)
    m = _conv2d(m,     _world_branch_4_W, _world_branch_4_b, stride=2)
    m = m.reshape(-1)
    m = np.maximum(0.0, m @ _world_branch_7_W.T + _world_branch_7_b)

    # Fusion head
    h = np.concatenate([s, w, m])
    h = np.maximum(0.0, h @ _fusion_0_W.T + _fusion_0_b)
    h = np.maximum(0.0, h @ _fusion_2_W.T + _fusion_2_b)
    return h @ _fusion_4_W.T + _fusion_4_b   # Q-values for 9 actions


# ── Agent ─────────────────────────────────────────────────────────────────────

class MyAgent(BaseAgent):
    """DQN (CNN) sailing agent — pure numpy, no torch."""

    def act(self, observation: np.ndarray) -> int:
        return int(np.argmax(_forward(observation)))

    def reset(self) -> None:
        pass

    def seed(self, seed=None) -> None:
        if seed is not None:
            np.random.seed(seed)
'''

    output_path.write_text(code, encoding='utf-8')
    print(f"  Generated -> {output_path}")
    print(f"  File size : {output_path.stat().st_size / 1024:.1f} KB")


# ── CLI ──────────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Export a trained DQN (CNN) checkpoint to a standalone numpy agent.")
    parser.add_argument("--checkpoint", required=True,
                        help="Path to .pt checkpoint (e.g. src/agents/dqn_cnn.pt)")
    parser.add_argument("--output", required=True,
                        help="Output .py path (e.g. src/agents/agent_DQN_cnn_numpy.py)")
    args = parser.parse_args()

    ckpt_path = Path(args.checkpoint)
    out_path  = Path(args.output)

    if not ckpt_path.exists():
        print(f"  Error: checkpoint not found at {ckpt_path}")
        sys.exit(1)

    print(f"  Loading checkpoint: {ckpt_path}")
    checkpoint = torch.load(str(ckpt_path), map_location='cpu', weights_only=False)
    state_dict = checkpoint['online_net']
    weights    = {k: v.cpu().numpy() for k, v in state_dict.items()}

    print("  Network weight shapes:")
    for key in _LAYER_KEYS:
        W = weights[f'{key}.weight']
        b = weights[f'{key}.bias']
        print(f"    {key+'.weight':35s}: {str(W.shape):20s}  bias: {b.shape}")

    generate_submission(weights, out_path)
    print("  Done. To validate:")
    print(f"    python src/test_agent_validity.py {out_path}")


if __name__ == "__main__":
    main()