"""
Standalone numpy DQN agent for the Sailing Challenge — Codabench submission.

*** THIS FILE IS AUTO-GENERATED by src/utils/export_to_numpy.py ***

Workflow:
  1. Train:  python src/utils/agent_DQN_v2_train.py
  2. Export: python src/utils/export_to_numpy.py \
                 --checkpoint src/agents/dqn_v2.pt \
                 --output     src/agents/agent_DQN_numpy.py
  3. Validate: python src/test_agent_validity.py src/agents/agent_DQN_numpy.py
  4. Submit:   zip agent_DQN_numpy.py  → upload to Codabench

Network: 70-dim features → 256 → 128 → 9 actions
No external dependencies beyond numpy.
"""

import base64
import numpy as np

try:
    from evaluator.base_agent import BaseAgent   # Codabench runtime
except ImportError:
    from agents.base_agent import BaseAgent       # local dev


# ── Placeholder weights (replace via export_to_numpy.py after training) ────────
# These zeros make the agent act randomly via argmax(0,...,0)=0 (always North).
# After training and export the block below is replaced with real weights.

_W0 = np.zeros((256, 70),  dtype=np.float32)
_b0 = np.zeros(256,        dtype=np.float32)
_W1 = np.zeros((128, 256), dtype=np.float32)
_b1 = np.zeros(128,        dtype=np.float32)
_W2 = np.zeros((9,   128), dtype=np.float32)
_b2 = np.zeros(9,          dtype=np.float32)


# ── Constants ──────────────────────────────────────────────────────────────────

_GOAL = np.array([64.0, 127.0])

_ACTIONS_VEC = np.array([
    ( 0.,  1.), ( 1.,  1.), ( 1.,  0.), ( 1., -1.),
    ( 0., -1.), (-1., -1.), (-1.,  0.), (-1.,  1.),
    ( 0.,  0.),
], dtype=np.float32)

_DIRS8 = [(0,1),(1,1),(1,0),(1,-1),(0,-1),(-1,-1),(-1,0),(-1,1)]


# ── Sailing physics ─────────────────────────────────────────────────────────────

def _compute_efficiencies(wind_vec):
    wspd = float(np.linalg.norm(wind_vec))
    if wspd < 1e-8:
        return np.full(9, 0.05, dtype=np.float32)
    wd   = wind_vec / wspd
    effs = np.zeros(9, dtype=np.float32)
    for i, a in enumerate(_ACTIONS_VEC):
        an = float(np.linalg.norm(a))
        if an < 1e-8:
            continue
        cos_a = float(np.clip(np.dot(a / an, wd), -1.0, 1.0))
        deg   = np.degrees(np.arccos(cos_a))
        if deg < 45:
            effs[i] = 0.05
        elif deg < 90:
            effs[i] = 0.5 + 0.5 * (deg - 45) / 45.0
        elif deg <= 135:
            effs[i] = 1.0
        else:
            effs[i] = 1.0 - 0.5 * (deg - 135) / 45.0
    return effs


# ── Feature extraction (70-dim) ────────────────────────────────────────────────

def _extract_features(obs):
    """
    70 physics-aware features from the 49158-dim raw observation.

    [0:3]   goal_dx/127, goal_dy/127, goal_dist/180
    [3:5]   x/127, y/127
    [5:7]   unit-vector to goal
    [7:10]  vx/8, vy/8, |v|/8
    [10:13] wx/15, wy/15, |w|/15
    [13:22] sailing efficiencies (9 actions)
    [22:46] obstacles in 8 dirs × 3 distances (4, 10, 20)
    [46:70] wind + obstacle at 8 points along path to goal
    """
    x, y   = float(obs[0]), float(obs[1])
    vx, vy = float(obs[2]), float(obs[3])
    wx, wy = float(obs[4]), float(obs[5])

    wind_field = obs[6          : 6 + 32768  ].reshape(128, 128, 2)
    world_map  = obs[6 + 32768  : 6 + 32768 + 16384].reshape(128, 128)

    ix = int(np.clip(x, 0, 127))
    iy = int(np.clip(y, 0, 127))

    gdx   = _GOAL[0] - x
    gdy   = _GOAL[1] - y
    gdist = float(np.sqrt(gdx**2 + gdy**2)) + 1e-8

    f_goal = np.array([gdx / 127.0, gdy / 127.0, gdist / 180.0], dtype=np.float32)
    f_pos  = np.array([x / 127.0,   y / 127.0],                  dtype=np.float32)
    f_dir  = np.array([gdx / gdist, gdy / gdist],                 dtype=np.float32)

    vn    = float(np.sqrt(vx**2 + vy**2))
    f_vel = np.array([vx / 8.0, vy / 8.0, vn / 8.0], dtype=np.float32)

    wspd   = float(np.sqrt(wx**2 + wy**2)) + 1e-8
    f_wind = np.array([wx / 15.0, wy / 15.0, wspd / 15.0], dtype=np.float32)

    f_eff = _compute_efficiencies(np.array([wx, wy]))

    DISTS = [4, 10, 20]
    f_obs = np.zeros(24, dtype=np.float32)
    for k, (dx_o, dy_o) in enumerate(_DIRS8):
        for j, d in enumerate(DISTS):
            nx = int(np.clip(ix + dx_o * d, 0, 127))
            ny = int(np.clip(iy + dy_o * d, 0, 127))
            f_obs[k * 3 + j] = world_map[ny, nx]

    FRACS = [0.05, 0.15, 0.30, 0.50, 0.70, 0.85, 0.95, 1.00]
    f_path = np.zeros(24, dtype=np.float32)
    for i, frac in enumerate(FRACS):
        px = int(np.clip(x + gdx * frac, 0, 127))
        py = int(np.clip(y + gdy * frac, 0, 127))
        f_path[3 * i]     = world_map[py, px]
        f_path[3 * i + 1] = wind_field[py, px, 0] / 15.0
        f_path[3 * i + 2] = wind_field[py, px, 1] / 15.0

    return np.concatenate([f_goal, f_pos, f_dir, f_vel, f_wind, f_eff, f_obs, f_path])


# ── Numpy forward pass ─────────────────────────────────────────────────────────

def _forward(x):
    h = np.maximum(0.0, x @ _W0.T + _b0)
    h = np.maximum(0.0, h @ _W1.T + _b1)
    return h @ _W2.T + _b2


# ── Agent ──────────────────────────────────────────────────────────────────────

class MyAgent(BaseAgent):
    """
    DQN sailing agent — pure numpy, no torch.
    Network: 70 → 256 → 128 → 9
    """

    def act(self, observation: np.ndarray) -> int:
        feats  = _extract_features(observation)
        q_vals = _forward(feats)
        return int(np.argmax(q_vals))

    def reset(self) -> None:
        pass

    def seed(self, seed=None) -> None:
        if seed is not None:
            np.random.seed(seed)