"""
Standalone numpy DQN (CNN) agent for the Sailing Challenge — Codabench submission.

*** THIS FILE IS AUTO-GENERATED by src/utils/export_dqn_cnn_to_numpy.py ***

Workflow:
  1. Train:    python src/utils/agent_DQN_train.py
  2. Export:   python src/utils/export_dqn_cnn_to_numpy.py \
                   --checkpoint src/agents/dqn_cnn.pt \
                   --output     src/agents/agent_DQN_cnn_numpy.py
  3. Validate: python src/test_agent_validity.py src/agents/agent_DQN_cnn_numpy.py
  4. Submit:   zip agent_DQN_cnn_numpy.py -> upload to Codabench

Architecture:
  scalar(6) -> Linear(6->32)->ReLU->Linear(32->64)->ReLU  --+
  wind(2,128,128) -> 3xConv2d+ReLU -> Linear->ReLU           +--> fusion(256->128->64->9)
  world(1,128,128) -> 3xConv2d+ReLU -> Linear->ReLU         --+
No external dependencies beyond numpy.
"""

import base64
import numpy as np

try:
    from evaluator.base_agent import BaseAgent   # Codabench runtime
except ImportError:
    from agents.base_agent import BaseAgent       # local dev


# ── Placeholder weights (replace via export_dqn_cnn_to_numpy.py after training) ─

# scalar_branch
_scalar_branch_0_W = np.zeros((32,   6),    dtype=np.float32)
_scalar_branch_0_b = np.zeros(32,           dtype=np.float32)
_scalar_branch_2_W = np.zeros((64,  32),    dtype=np.float32)
_scalar_branch_2_b = np.zeros(64,           dtype=np.float32)

# wind_branch (CNN)
_wind_branch_0_W = np.zeros((8,   2,  8, 8), dtype=np.float32)
_wind_branch_0_b = np.zeros(8,               dtype=np.float32)
_wind_branch_2_W = np.zeros((16,  8,  4, 4), dtype=np.float32)
_wind_branch_2_b = np.zeros(16,              dtype=np.float32)
_wind_branch_4_W = np.zeros((32, 16,  3, 3), dtype=np.float32)
_wind_branch_4_b = np.zeros(32,              dtype=np.float32)
_wind_branch_7_W = np.zeros((128, 1152),     dtype=np.float32)
_wind_branch_7_b = np.zeros(128,             dtype=np.float32)

# world_branch (CNN)
_world_branch_0_W = np.zeros((8,   1,  8, 8), dtype=np.float32)
_world_branch_0_b = np.zeros(8,               dtype=np.float32)
_world_branch_2_W = np.zeros((16,  8,  4, 4), dtype=np.float32)
_world_branch_2_b = np.zeros(16,              dtype=np.float32)
_world_branch_4_W = np.zeros((16, 16,  3, 3), dtype=np.float32)
_world_branch_4_b = np.zeros(16,              dtype=np.float32)
_world_branch_7_W = np.zeros((64, 576),       dtype=np.float32)
_world_branch_7_b = np.zeros(64,              dtype=np.float32)

# fusion head
_fusion_0_W = np.zeros((128, 256), dtype=np.float32)
_fusion_0_b = np.zeros(128,        dtype=np.float32)
_fusion_2_W = np.zeros((64,  128), dtype=np.float32)
_fusion_2_b = np.zeros(64,         dtype=np.float32)
_fusion_4_W = np.zeros((9,   64),  dtype=np.float32)
_fusion_4_b = np.zeros(9,          dtype=np.float32)


# ── Numpy conv2d (Conv2d + ReLU, no padding) ──────────────────────────────────

def _conv2d(x, W, b, stride):
    """x: (C_in,H,W), W: (C_out,C_in,kH,kW), b: (C_out,) -> (C_out,H_out,W_out) after ReLU."""
    x = np.ascontiguousarray(x, dtype=np.float32)
    C_in, H, Wi = x.shape
    C_out, _, kH, kW = W.shape
    Ho = (H  - kH) // stride + 1
    Wo = (Wi - kW) // stride + 1
    shape   = (Ho, Wo, C_in, kH, kW)
    strides = (x.strides[1] * stride, x.strides[2] * stride,
               x.strides[0], x.strides[1], x.strides[2])
    windows = np.lib.stride_tricks.as_strided(x, shape=shape, strides=strides)
    out = windows.reshape(Ho * Wo, -1) @ W.reshape(C_out, -1).T + b
    return np.maximum(0.0, out.reshape(Ho, Wo, C_out).transpose(2, 0, 1))


# ── Numpy forward pass ────────────────────────────────────────────────────────

def _forward(obs):
    scalar     = obs[:6          ].astype(np.float32)
    wind_flat  = obs[6:6+32768   ].astype(np.float32)
    world_flat = obs[6+32768:6+32768+16384].astype(np.float32)

    wind  = wind_flat.reshape(2, 128, 128)
    world = world_flat.reshape(1, 128, 128)

    # Scalar branch
    s = np.maximum(0.0, scalar @ _scalar_branch_0_W.T + _scalar_branch_0_b)
    s = np.maximum(0.0, s      @ _scalar_branch_2_W.T + _scalar_branch_2_b)

    # Wind branch (CNN)
    w = _conv2d(wind, _wind_branch_0_W, _wind_branch_0_b, stride=4)
    w = _conv2d(w,    _wind_branch_2_W, _wind_branch_2_b, stride=2)
    w = _conv2d(w,    _wind_branch_4_W, _wind_branch_4_b, stride=2)
    w = w.reshape(-1)
    w = np.maximum(0.0, w @ _wind_branch_7_W.T + _wind_branch_7_b)

    # World branch (CNN)
    m = _conv2d(world, _world_branch_0_W, _world_branch_0_b, stride=4)
    m = _conv2d(m,     _world_branch_2_W, _world_branch_2_b, stride=2)
    m = _conv2d(m,     _world_branch_4_W, _world_branch_4_b, stride=2)
    m = m.reshape(-1)
    m = np.maximum(0.0, m @ _world_branch_7_W.T + _world_branch_7_b)

    # Fusion head
    h = np.concatenate([s, w, m])
    h = np.maximum(0.0, h @ _fusion_0_W.T + _fusion_0_b)
    h = np.maximum(0.0, h @ _fusion_2_W.T + _fusion_2_b)
    return h @ _fusion_4_W.T + _fusion_4_b   # Q-values for 9 actions


# ── Agent ─────────────────────────────────────────────────────────────────────

class MyAgent(BaseAgent):
    """DQN (CNN) sailing agent — pure numpy, no torch."""

    def act(self, observation: np.ndarray) -> int:
        return int(np.argmax(_forward(observation)))

    def reset(self) -> None:
        pass

    def seed(self, seed=None) -> None:
        if seed is not None:
            np.random.seed(seed)